### ISSUE TITLE
USWDS dist/ folder not created automatically in build server

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist-uswds-jekyll#1]
For some reason the USWDS library is not automatically built on the Federalist build server, although it works locally. This means that the dist/ is not created and the compiled assets are not available.

To resolve this, I step directly into the folder and run the build command.
https://github.com/18F/federalist-uswds-jekyll/commit/83b2e18d699598667afcb8a39e2c92d8f73ff5b5

Ideally, this would not be necessary.

**Comment by adborden** [comment]
Fixed in https://github.com/18F/federalist-uswds-jekyll/pull/4
