### ISSUE TITLE
Implement search.gov based site search

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#12]
As a developer, I would want documentation on how to use search.gov with the federalist-uswds-jekyll template so that I can provide site search on my Federalist site for my users.

- [x] Add a default search experience to the template with minimal configuration.
- [x] Document any steps that a developer would need to take to setup search.gov for their site.
- [x] Search results should be displayed within the site (not forwarded to search.gov).

**Comment by adborden** [comment]
@eddietejeda I just confirmed that type-ahead is working.

The initial implementation I used was search.gov's recommended one. The form action does a GET to search.gov/search.

We wrote in the criteria that we wanted an "in-site" experience, fetching search results via API and rendering them in JS. I think we might want to hold off on that until we get more feedback from users. @eddietejeda what do you think, okay to close or should I go ahead with the JS implementation?

**Comment by eddietejeda** [comment]
Hey @adborden, agreed. Can you make the JS another issue?

**Comment by adborden** [comment]
:heavy_check_mark:
