### ISSUE TITLE
Sticky Sidnav

### ISSUE THREAD

**Issue by idmken** [18F/federalist-uswds-jekyll#121]
Is this possible? The non-federalist template allows this.

https://github.com/18F/uswds-jekyll

Trying to mimic it unless there is another way to do it. Thank you!

**Comment by davemcorwin** [comment]
While both repositories build off of USWDS, https://github.com/18F/uswds-jekyll takes a very different approach than this one and they both have pros and cons. This repository is less opinionated but more flexible and is meant to act as a "starter" to get you up and running quickly, but after that, it's your code and you can change it as you see fit.

**Comment by davemcorwin** [comment]
@idmken I'm going to close this issue as there is nothing to do here. As mentioned in my previous comment, this is meant to be a "starter" and you are free to modify it as you see fit from there.
