### ISSUE TITLE
Change Background Image

### ISSUE THREAD

**Issue by idmken** [18F/federalist-uswds-jekyll#122]
Sorry for the simple question, but where is the background image linked?

**Comment by davemcorwin** [comment]
Assuming you are referring the background image in the Hero component, the image itself comes from and lives within USWDS. You can modify it in a couple different ways:

1. If you're using the sass, set a sass variable  `$theme-hero-image: asset_path("your-image.png");`

OR

2. if you're just using css, override it:

.usa-hero {
  background-image: asset_url("your-image.png
  background-position: 50%;
  background-size: cover;
}
