### ISSUE TITLE
Current link in header not working

### ISSUE THREAD

**Issue by maya** [18F/federalist-uswds-jekyll#15]
when you go to the old template docs page you see the header link "Documentation" highlighted. That functionality isn't on the 2.0 site:

https://federalist-uswds-template.18f.gov/docs/ vs. https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/example-page/

**Comment by adborden** [comment]
I think this _is_ working (or was recently fixed). example-page does not have a sidenav, but [example-page-with-sidenav](https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/example-page-with-sidenav/) does, and has the current nav highlighted.

**Comment by adborden** [comment]
Ah, I see, thanks!
