### ISSUE TITLE
Update in-page side navigation on example page to match content.

### ISSUE THREAD

**Issue by maya** [18F/federalist-uswds-jekyll#16]
On the old template, sections had the ability to be linked from the sidebar navigation, but I don't see this on the 2.0 template: 

https://federalist-uswds-template.18f.gov/docs/#section-two vs https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/example-page-with-sidenav/

Update the sidenav content to match the example page so that the side navigation works correctly.

**Comment by adborden** [comment]
Thanks for reporting! This does [work](https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/example-page-with-sidenav/#section-heading-h2), but the sidenav content does not match the headings of the content. I'm going to update the issue to fix the sidenav.
