### ISSUE TITLE
News page visual design review

### ISSUE THREAD

**Issue by maya** [18F/federalist-uswds-jekyll#17]
The USWDS doesn't currently have a blog page template. Bc of this, it might be good to review the design with a visual designer in the design lab.

Here's a previous design for search results page, which is pretty similar to a blog page: https://github.com/uswds/uswds/issues/77

**Comment by eddietejeda** [comment]
Progress being tracked here: https://github.com/18F/design-lab/issues/45

That repository is private, so here is the latest draft:

![](https://user-images.githubusercontent.com/23194720/53276221-31e79680-36cc-11e9-942d-c6fbe40a129b.jpg)

**Comment by eddietejeda** [comment]
This has been merged!
