### ISSUE TITLE
Research the implementation for an in-site search experience for search.gov

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#20]
We implemented basic [search.gov](https://github.com/18F/federalist-uswds-jekyll/issues/12) integration. However, we can provide a "richer" search experience by using the Search.gov API and rendering search results via JavaScript.

We should do some research to figure out how the search experience can be improved for users.

- [ ] Identify user needs around search experience.
- [ ] Create a new issue with implementation steps and acceptance criteria

**Comment by eddietejeda** [comment]
This is done.
https://github.com/18F/federalist-uswds-jekyll/releases/tag/v1.2.0
