### ISSUE TITLE
Transient jekyll starter build issues

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-jekyll#223]
#### User Story

As a user I want builds to succeed consistently when there are no problems.

#### Background (Optional)

https://federalistapp.18f.gov/sites/559/builds/215487/logs

2021-11-16 17:52:43 INFO [build-jekyll] on line 139 of /tmp/work/site_repo/node_modules/uswds/dist/scss/core/_notifications.scss
2021-11-16 17:52:43 INFO [build-jekyll] from line 21 of /tmp/work/site_repo/node_modules/uswds/dist/scss/packages/_required.scss
2021-11-16 17:52:43 INFO [build-jekyll] from line 5 of /tmp/work/site_repo/node_modules/uswds/dist/scss/uswds.scss
2021-11-16 17:52:43 INFO [build-jekyll] from line 9 of /tmp/work/site_repo/_assets/css/index.scss
2021-11-16 17:52:44 INFO [build-jekyll] [31m  Liquid Exception: String can't be coerced into Integer in /_layouts/base.html[0m
2021-11-16 17:52:44 INFO [build-jekyll] jekyll 3.9.1 | Error:  String can't be coerced into Integer
2021-11-16 17:52:44 INFO [build-jekyll] /usr/local/rvm/gems/ruby-2.7.4/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `-': String can't be coerced into Integer (TypeError)
2021-11-16 17:52:44 INFO [build-je)

#### Acceptance Criteria

- [x] Builds don't randomly fail
- [x] Change made live via deploy of starter.

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by svenaas** [comment]
Well, I reproduced this locally. 

1. cloned https://github.com/18F/federalist-uswds-jekyll
2. `npm install`
3. `bundle install`
4. `bundle exec jekyll serve`

```
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: String can't be coerced into Integer in /_layouts/base.html
jekyll 3.9.1 | Error:  String can't be coerced into Integer
```

I get the same result with `npm start` (and so I should; it calls the same command):
```
> federalist-uswds-jekyll@1.3.0 start
> bundle exec jekyll serve

Configuration file: /Users/sveneaas/Projects/federalist-uswds-jekyll/_config.yml
            Source: /Users/sveneaas/Projects/federalist-uswds-jekyll
       Destination: /Users/sveneaas/Projects/federalist-uswds-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: String can't be coerced into Integer in /_layouts/base.html
jekyll 3.9.1 | Error:  String can't be coerced into Integer
```

**Comment by svenaas** [comment]
Not the same problem, but the same kind of variability in whether it occurs: https://talk.jekyllrb.com/t/jekyll-scss-encountered-an-error/5719

I've seen multiple references to race condition-y things during Jekyll processing.

**Comment by svenaas** [comment]
I am nearly certain this is a race condition during the multithreaded ruby-sass build. From `jekyll build` to `jekyll build` it either fails quickly or builds successfully (in 15–20 seconds on my laptop). 

When it fails the trace shows that the point of failure is in a ruby-sass internal function:
```
gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `-'
gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `basically_equal?'
```
This function is called deep in a `visit` / `render` stack during sass tree traversal prompted by liquid rendering. I haven't found an easy way to figure out exactly what string is being passed into `basically_equal?` or from where but the unpredictable but predictably intermittent occurrence suggests that is a matter of which rendering step completes first.

As of this writing we're on Jekyll 3.9.1 and, perhaps more importantly, ruby-sass 3.7.4, which is the April 2019 EOL release of that Sass processor. This issue might be resolved if we switched to Dart or to Jekyll's jekyll-sass-converter for Sass processing.

**Comment by svenaas** [comment]
I'm putting this back in the backlog unless and until one of us has a brainstorm. There are other things to work on.

**Comment by caleywoods** [comment]
> I am nearly certain this is a race condition during the multithreaded ruby-sass build. From `jekyll build` to `jekyll build` it either fails quickly or builds successfully (in 15–20 seconds on my laptop).
> 
> When it fails the trace shows that the point of failure is in a ruby-sass internal function:
> 
> ```
> gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `-'
> gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `basically_equal?'
> ```
> 
> This function is called deep in a `visit` / `render` stack during sass tree traversal prompted by liquid rendering. I haven't found an easy way to figure out exactly what string is being passed into `basically_equal?` or from where but the unpredictable but predictably intermittent occurrence suggests that is a matter of which rendering step completes first.
> 
> As of this writing we're on Jekyll 3.9.1 and, perhaps more importantly, ruby-sass 3.7.4, which is the April 2019 EOL release of that Sass processor. This issue might be resolved if we switched to Dart or to Jekyll's jekyll-sass-converter for Sass processing.

This was pretty much the conclusion that I reached as well, some kind of race condition that results in SASS being fed input that hadn't quite been finished being de-tokenized/parsed by Liquid.

**Comment by caleywoods** [comment]
@svenaas I attempted downgrading sass during my troubleshooting and went down a single version to 3.7.3 and then to 3.7.2 just to see what the outcome would be and encountered the same intermittent initial build failure.

Since we're wanting to use Jekyll and the USWDS template, I am going to investigate replacing sass with either of the two solutions you mentioned and potentially being in a position to contribute it back to the template and address this issue.

**Comment by davemcorwin** [comment]
Thanks @caleywoods , we're happy to incorporate whatever solution you can come up with. Right now, the SASS processing is handled at a high level by `jekyll-assets`, but that provides some other niceties that we don't want to lose. Perhaps we can exclude the SASS processing from `jekyll-assets` and handle it elsewhere.
