### ISSUE TITLE
Fix active state for Blog page nav link

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-jekyll#23]
Currently, the nav link does not show the "active" state when on the blog page (image below), it should. This is slightly complicated by the blog page living at `blog/index.html` instead of `blog.html` which the current logic in `_includes/menu.html` cannot handle.

![blog](https://user-images.githubusercontent.com/6662371/54702573-59c3f180-4af4-11e9-8de7-4de33e13f7e1.png)

**Comment by eddietejeda** [comment]
Tracking here instead: https://github.com/18F/federalist-uswds-jekyll/issues/14
