### ISSUE TITLE
Remove CSS copy-based build step

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#5]
@eddietejeda can we get rid of the css copy in the build step? Shouldn't we be encouraging people to use Jekyll's built-in sass compilation rather than working in CSS and then copying it over to assets? The Jekyll build will do that automatically.

**Comment by eddietejeda** [comment]
Good point. Yes, lets do it the Jekyll way.

**Comment by adborden** [comment]
The Jekyll way is just having a `_sass` dir.
