### ISSUE TITLE
Remove `use graphql: true` from Netlify CMS config (jekyll)

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist-uswds-jekyll#56]

**Comment by amirbey** [comment]
#### User Story

A user should be able to delete unpublished changes.

#### Background (Optional)

This experimental feature is preventing users from delete unpublished changes

#### Acceptance Criteria

- [ ] verify ability to delete unpublished changes
- [ ] Change made live via deploy of jekyll starter template

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

#### Implementation outline (if higher than "low" effort):

- [ ] remove graphql:true from config
