### ISSUE TITLE
Avoid shipping USWDS SASS files to the finished site

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#6]
We should copy the SASS files to `_sass` so they can be used at build time, but we don't want to ship them in the finished site.

## Repro

1. npm run build
2. ls _site/assets/scss

## Expected

scss directory does not exist

## Actual

scss exists with all the SASS files.

**Comment by eddietejeda** [comment]
@adborden is this still relevant?

**Comment by adborden** [comment]
Yes, this bug still exists.

**Comment by adborden** [comment]
nm, this is fixed if you clone from a fresh repo.
