### ISSUE TITLE
sidenav.html needs more work please

### ISSUE THREAD

**Issue by bruce-usab** [18F/federalist-uswds-jekyll#78]
I do not think the `_includes/sidenav.html` file is working as expected.

I had expected to find liquid  loops `{% for …` and conditionals `{% if …` building the sidebar navigation iteratively for each page with `sidenav: true` set in the front matter.  One main concern, I think, is that `class="usa-current"` should be assigned dynamically. 

Canonical instructions are available [here](https://jekyllrb.com/tutorials/navigation/#scenario-4-three-level-navigation-list), but I am afraid this is all a bit too new to me for me at the moment.  I will note that the primary navigation section of `_config.yaml` file makes sense to me and follows the model of those canonical instructions.

I will also note that the [rendered page](https://federalist-ce810add-9092-4627-8246-9b65cf94623c.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/) is odd in that it displays one “Current page”, one “Child link” and one “Grandchild link” all highlighted as the same time.  I think that would be the expected behavior only if `_pages/document_with_sidenav.md` had its front matter `title` property set to “Grandchild Link”.  As it is, the `class="usa-current"` bit is  hard coded in three places in `navbar.html`.  The static assignment of that class seems, to me, to be a mistake.

Please advise or provide a sample navbar.html that uses liquid examples.

**Comment by davemcorwin** [comment]
Hi @bruce-usab thanks for bringing this up. We actually have an outstanding issue to improve the implementation of the nav in the document pages over in the Gatsby starter repo (https://github.com/18F/federalist-uswds-gatsby/issues/24) but its helpful to have one here to track it as well.

In the meantime, you should be able to use the implementation of the primary and secondary navigation in "_includes/menu/html" as an example of how to do this.
