### ISSUE TITLE
Default view for blog posts on home page?

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist-uswds-jekyll#8]
Recent blog posts could be handled like this by default: https://www.cio.gov I've seen it done like this for multiple sites. What do you think @adborden ?

**Comment by adborden** [comment]
You mean having a section on the homepage that highlights recent blog posts? That makes sense to me.

![screenshot from 2019-01-18 16-09-39](https://user-images.githubusercontent.com/509703/51418946-9c407080-1b3b-11e9-8575-70080dec9001.png)

**Comment by eddietejeda** [comment]
See https://github.com/18F/design-lab/issues/45 for more information.

**Comment by eddietejeda** [comment]
Issue has moved here: github.com/18f/federalist-uswds-jekyll/17

**Comment by eddietejeda** [comment]
This is done.
