### ISSUE TITLE
Separate Jekyll content from non-Jekyll files

### ISSUE THREAD

**Issue by adborden** [18F/federalist-uswds-jekyll#9]
Proposal: Move all the Jekyll site content (index.html, _layouts, _includes, assets, etc) to `pages/` using the `source` configuration option and remove the `_pages` collection.

Some rationale:
1. Jekyll has a built-in collection `site.pages` that contains all the pages in the site. Using `_pages` actually overrides that built-in collection.
1. This avoids having pages like index.html in the root directory.
1. The directory structure under `pages/` mirrors the site structure making it easy to figure out where to edit page content.
1. If you prefer a flat structure, you can still keep everything flat in `pages/` and use `permalink` frontmatter.
1. This keeps the Jekyll content separate from boilerplate files like README.md, Gemfile, node_modules, etc.
1. This keeps the Jekyll build files separate from the npm build files in `src/`.
1. This is similar to existing 18F templates used in the past (although they did not use the `source` configuration and specified `permalink` everywhere).

The structure ends up looking like [this](https://gist.github.com/adborden/a52df5afd7213728674b3254fc55208c).

**Comment by eddietejeda** [comment]
I like this idea. I don't like the default structure of Jekyll, especially that "pages" are not always in _pages. But I want to think this over a bit more. Lets discuss in our next group chat.

Something to keep in mind is the [18F website](https://github.com/18F/18f.gsa.gov
https://github.com/18F/18f.gsa.gov/blob/master/_config.yml#L35) takes an approach similar that to what we already have.

**Comment by adborden** [comment]
Right, many of the old sites from 18F also follow this convention. I believe it was from an earlier Jekyll where certain features didn't exist yet. I don't know why they did it this way. Many were also based on the go-script, too. I think it is all legacy that they should move away from it.
